[package]
name = "ktv-casting"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test_rupnp"
path = "test_rupnp.rs"

[dependencies]
actix-files = "0.6.9"
actix-web = "4.12.1"
futures = "0.3.31"
reqwest = { version = "0.13.1", features = ["json"] }
rupnp = "3.0.0"
tokio = { version = "1.49.0", features = ["full"] }
upnp-client = "0.1.11"
urlencoding = "2.1.3"
